/**
 * Serve the client SPA.
 *
 * Three modes, in priority order:
 *   1. Compiled binary: `embedded-assets.ts` exists and exports a populated
 *      Map. Serve from there. (Generated by scripts/embed-assets.ts.)
 *   2. Production-on-disk: packages/client/dist exists. Serve from there.
 *   3. Dev placeholder: show a page telling the user to run the dev client.
 *
 * The embedded-assets.ts file is auto-generated and may not exist during
 * dev; we use a dynamic import wrapped in try/catch so it's optional.
 */

import { serveStatic } from 'hono/bun';
import type { Hono } from 'hono';
import { existsSync } from 'node:fs';
import { join, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

export async function mountStatic(app: Hono): Promise<void> {
  // Mode 1: try embedded assets (compiled binary path)
  const embedded = await tryLoadEmbedded();
  if (embedded && embedded.size > 0) {
    mountEmbedded(app, embedded);
    return;
  }

  // Mode 2: try on-disk dist
  const here = dirname(fileURLToPath(import.meta.url));
  const candidates = [
    resolve(here, '../../client/dist'),
    resolve(here, '../../../client/dist'),
    resolve(process.cwd(), 'packages/client/dist'),
  ];
  const root = candidates.find((p) => existsSync(p));
  if (root) {
    mountFromDisk(app, root);
    return;
  }

  // Mode 3: dev placeholder
  mountPlaceholder(app);
}

async function tryLoadEmbedded(): Promise<Map<string, string> | null> {
  try {
    // The variable indirection prevents Bun's bundler from failing the
    // build when this file doesn't exist (it's only generated for compile).
    const modPath = './embedded-assets.ts';
    const mod: { embeddedAssets?: Map<string, string> } = await import(
      /* @vite-ignore */ modPath
    );
    return mod.embeddedAssets ?? null;
  } catch {
    return null;
  }
}

function mountEmbedded(app: Hono, assets: Map<string, string>): void {
  app.get('*', async (c) => {
    const url = new URL(c.req.url);
    let path = url.pathname;
    // SPA fallback - any non-asset path serves index.html
    if (path === '/' || !assets.has(path)) {
      path = '/index.html';
    }
    const filePath = assets.get(path);
    if (!filePath) {
      return c.text('Not found', 404);
    }
    const file = Bun.file(filePath);
    const type = inferContentType(path);
    return new Response(file, {
      headers: { 'Content-Type': type },
    });
  });
}

function mountFromDisk(app: Hono, root: string): void {
  app.use(
    '/*',
    serveStatic({
      root,
      onNotFound: () => {},
    }),
  );
  app.get('*', async (c) => {
    const indexPath = join(root, 'index.html');
    const file = Bun.file(indexPath);
    return c.html(await file.text());
  });
}

function mountPlaceholder(app: Hono): void {
  app.get('*', (c) =>
    c.html(`<!doctype html>
<html>
<head><title>review-app</title>
<style>body{font-family:system-ui;max-width:540px;margin:4rem auto;padding:0 1rem;color:#333}</style>
</head>
<body>
<h1>review-app agent is running</h1>
<p>The client build is not present. Run:</p>
<pre>bun run --filter client dev</pre>
<p>...then open <a href="http://localhost:5173">http://localhost:5173</a> for the dev client (it proxies to this agent on port 7676).</p>
<p>Or build the client for production:</p>
<pre>bun run build:client</pre>
</body></html>`),
  );
}

function inferContentType(path: string): string {
  if (path.endsWith('.html')) return 'text/html; charset=utf-8';
  if (path.endsWith('.js') || path.endsWith('.mjs'))
    return 'application/javascript; charset=utf-8';
  if (path.endsWith('.css')) return 'text/css; charset=utf-8';
  if (path.endsWith('.json')) return 'application/json';
  if (path.endsWith('.svg')) return 'image/svg+xml';
  if (path.endsWith('.png')) return 'image/png';
  if (path.endsWith('.jpg') || path.endsWith('.jpeg')) return 'image/jpeg';
  if (path.endsWith('.woff2')) return 'font/woff2';
  if (path.endsWith('.woff')) return 'font/woff';
  if (path.endsWith('.ico')) return 'image/x-icon';
  if (path.endsWith('.map')) return 'application/json';
  return 'application/octet-stream';
}
