#!/usr/bin/env bun
/**
 * Build helper: after `bun run build:client`, this script generates
 * `packages/agent/src/embedded-assets.ts` which `import`s every file
 * from `packages/client/dist/` using Bun's `with { type: "file" }`
 * syntax. The result is that `bun build --compile` bakes the client
 * assets into the binary.
 *
 * Run sequence:
 *   bun run build:client    -> produces packages/client/dist
 *   bun run scripts/embed-assets.ts  (this file)
 *   bun run package:macos   -> single binary including the SPA
 *
 * The generated module exports a Map<string, BunFile> keyed by the
 * URL-style asset path ("/index.html", "/assets/main-abc123.js", etc.).
 * `agent/src/static.ts` reads from that map at runtime in compiled mode.
 */

import { readdir } from 'node:fs/promises';
import { join, relative } from 'node:path';

const CLIENT_DIST = join(import.meta.dir, '..', 'packages', 'client', 'dist');
const OUT_PATH = join(
  import.meta.dir,
  '..',
  'packages',
  'agent',
  'src',
  'embedded-assets.ts',
);

async function* walk(dir: string): AsyncGenerator<string> {
  const entries = await readdir(dir, { withFileTypes: true });
  for (const e of entries) {
    const p = join(dir, e.name);
    if (e.isDirectory()) {
      yield* walk(p);
    } else {
      yield p;
    }
  }
}

async function main() {
  const files: string[] = [];
  for await (const p of walk(CLIENT_DIST)) {
    files.push(p);
  }
  files.sort();

  const imports: string[] = [];
  const entries: string[] = [];

  files.forEach((abs, i) => {
    const rel = '/' + relative(CLIENT_DIST, abs).replace(/\\/g, '/');
    const varName = `asset_${i}`;
    // Path relative to the generated file's location
    const importPath = '../../client/dist/' + relative(CLIENT_DIST, abs).replace(/\\/g, '/');
    imports.push(
      `import ${varName} from '${importPath}' with { type: 'file' };`,
    );
    entries.push(`  [${JSON.stringify(rel)}, ${varName}],`);
  });

  const source = `// AUTO-GENERATED by scripts/embed-assets.ts. Do not edit.
// Re-run \`bun run scripts/embed-assets.ts\` after rebuilding the client.

${imports.join('\n')}

/** Map from URL path (e.g. "/index.html", "/assets/foo.js") to a Bun file path. */
export const embeddedAssets = new Map<string, string>([
${entries.join('\n')}
]);
`;

  await Bun.write(OUT_PATH, source);
  console.log(`Wrote ${OUT_PATH}`);
  console.log(`Embedded ${files.length} files`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
